### PR TITLE
#1469: remove unreachable null check in AsmUnknownAttribute.write()

### LINKED ISSUE #1469: Unreachable null check in `AsmUnknownAttribute.write()`
## What happens

In [`AsmUnknownAttribute.java`](https://github.com/objectionary/jeo-maven-plugin/blob/master/src/main/java/org/eolang/jeo/representation/asm/AsmUnknownAttribute.java), the constructor assigns `this.data` via:

```java
this.data = Optional.ofNullable(data).orElse(AsmUnknownAttribute.EMPTY).clone();
```

This guarantees `this.data` is never `null` — it falls back to `EMPTY` (an empty `byte[]`) when the argument is `null`.

Yet `write()` still checks on line 82:

```java
if (this.data == null) {
    throw new IllegalArgumentException(
        String.format("Attribute data is null for type `%s`", this.type)
    );
}
```

This branch is unreachable: the condition can never be `true`. The check misleads readers into thinking `null` is possible after construction, and the exception can never actually be thrown to help diagnose a real problem.

## What should happen

The dead null check in `write()` should be removed. The constructor already enforces the non-null invariant via `orElse(EMPTY)`.

I would like to fix this issue if you confirm it's a bug.

### PR DESCRIPTION
**Pull request by morphqdd**
The constructor assigns `this.data` via:

```java
this.data = Optional.ofNullable(data).orElse(AsmUnknownAttribute.EMPTY).clone();
```

This guarantees `this.data` is never `null` after construction. The `null` check in `write()` is therefore unreachable and has been removed.

A test is added to verify that `write()` works correctly when constructed with `null` data (falls back to empty array) and with non-empty data.

Closes #1469

## Summary by CodeRabbit

* **Tests**
  * Added comprehensive test coverage for attribute data writing with null and non-null inputs.

* **Bug Fixes**
  * Improved null data handling in attribute writing operations.

### CODE REVIEW

**Comment by morphqdd** [comment]
@yegor256, all CI checks are passing. Could you please review?

**Comment by yegor256** [comment]
@volodya-lombrozo FYI

File: src/test/java/org/eolang/jeo/representation/asm/AsmUnknownAttributeTest.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+import org.objectweb.asm.ByteVector;
+
+/**
+ * Test case for {@link AsmUnknownAttribute}.
+ * @since 0.15.0
+ */
+final class AsmUnknownAttributeTest {
+
+    /**
+     * Verifies that {@link AsmUnknownAttribute#write} returns a non-null
```
Comment (volodya-lombrozo) [inline src/test/java/org/eolang/jeo/representation/asm/AsmUnknownAttributeTest.java]: @morphqdd No need to add javadocs here. The test is clear by itself.

File: src/test/java/org/eolang/jeo/representation/asm/AsmUnknownAttributeTest.java [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+        MatcherAssert.assertThat(
+            "Writing attribute with null data should produce empty ByteVector, not throw",
+            result,
+            Matchers.notNullValue()
+        );
+    }
+
+    /**
+     * Verifies that {@link AsmUnknownAttribute#write} returns a non-null
+     * {@link ByteVector} when the attribute data is non-empty.
```
Comment (volodya-lombrozo) [inline src/test/java/org/eolang/jeo/representation/asm/AsmUnknownAttributeTest.java]: @morphqdd No need to add javadocs here. The test is clear by itself.

File: src/test/java/org/eolang/jeo/representation/asm/AsmUnknownAttributeTest.java [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+package org.eolang.jeo.representation.asm;
+
+import org.hamcrest.MatcherAssert;
+import org.hamcrest.Matchers;
+import org.junit.jupiter.api.Test;
+import org.objectweb.asm.ByteVector;
+
+/**
+ * Test case for {@link AsmUnknownAttribute}.
+ * @since 0.15.0
```
Comment (volodya-lombrozo) [inline src/test/java/org/eolang/jeo/representation/asm/AsmUnknownAttributeTest.java]: @morphqdd the latest version is `0.15.1`, I guess we need to set `o.16.o` or `o.15.1` here?

File: src/test/java/org/eolang/jeo/representation/asm/AsmUnknownAttributeTest.java [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+        );
+    }
+
+    /**
+     * Verifies that {@link AsmUnknownAttribute#write} returns a non-null
+     * {@link ByteVector} when the attribute data is non-empty.
+     */
+    @Test
+    void writesNonEmptyData() {
+        final byte[] data = {0x01, 0x02, 0x03};
```
Comment (volodya-lombrozo) [inline src/test/java/org/eolang/jeo/representation/asm/AsmUnknownAttributeTest.java]: @morphqdd do we need these variables?

https://www.yegor256.com/2015/09/01/redundant-variables-are-evil.html

**Review by volodya-lombrozo — CHANGES_REQUESTED** [review]
@morphqdd Great thanks for the contribution! Just several small suggestions.

File: src/test/java/org/eolang/jeo/representation/asm/AsmUnknownAttributeTest.java (hunk 3 above)
Comment (morphqdd) [reply src/test/java/org/eolang/jeo/representation/asm/AsmUnknownAttributeTest.java]: i will set 0.16.0

**Comment by morphqdd** [comment]
@volodya-lombrozo, I've addressed all your comments — removed the javadocs, fixed the `since` version to `0.16.0`, inlined the variables, and removed the unused import that was caught by qulice. Could you please take another look?

**Comment by volodya-lombrozo** [comment]
@morphqdd Looks good to me. Thank you for the contribution!

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by 0crat** [comment]
@volodya-lombrozo Thanks for the review! 🎉 You've earned **+7 points** for this contribution: **+12** as the base reward, then **-5** deducted due to having only **4 comments** (our policy requires at least 12 for full points). Your running score is [+265](https://www.eolang.org/zerocracy/objectionary-vitals.html) - keep up the great work and remember that more reviewer engagement means higher rewards! Don't forget to check your [Zerocracy account](https://www.zerocracy.com/) too.

**Comment by 0crat** [comment]
@morphqdd Excellent work! 🎉 You've earned **+16 points** for this contribution. [Keep up the momentum](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) with more quality submissions! Your total score has reached [+152](https://www.eolang.org/zerocracy/objectionary-vitals.html) - check your [Zerocracy account](https://www.zerocracy.com/) for updates.
